name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@update-cppcheck
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          github_username: "deep5050"
          github_email: "dipankarpal5050@gmail.com"
          commit_msg: "cppcheck test push"
          max_ctu_depth: '4'
      - name: Commit report file
        run: |
          git config --local user.email "dipankarpal5050@gmail.com"
          git config --local user.name "deep5050"
          git add --all
          git commit -m "report added/updated" --quiet
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

